import { DefaultQuizLayoutBuilder } from "../../../defaultQuizLayout"
import { getRandomPhoto } from "../../../backgrounds"
import { floatTimedCompareStrictlyEqual, TimedValue } from "../../../evaluators/evaluators"
import { AnswerKey, NonNegativeNumber, QuizBuilder } from "../../../quiz"
import { TextRenderer } from "../../../renderers/TextRenderer"
import { AutofillEnumFetcher } from "../../../response fetchers/autofill enum fetcher"
import { MultipleChoiceFetcher } from "../../../response fetchers/multiple choice fetcher"
import { DefaultCoordinator } from "../../../TrainingCoordinator"

const timeLimitSeconds = new NonNegativeNumber(5)

type WordTranslation = string[]

// TODO: Some of these definitions are ambiguous or duplicated, fix that

const prepositions: [string, WordTranslation][] = [
	['うえ', ["up; above; over; on top of"]],
	['した', ["down; below; under; beneath"]],
	['なか', ["inside; in; within; center"]],
	['よこ', ["beside; side; width"]],
	['そと', ["outside; exterior; outdoors"]],
	['まえ', ["front; before; in front of"]],
	['うしろ', ["back; behind; rear"]],
	['みぎ', ["right-hand side"]],
	['ひだり', ["left-hand side"]],
	// ['となり', ["next to; beside"]],
	// ['ちかく', ["near; close"]],
	// ['とおく', ["far; distant"]],
	// ['あいだ', ["between; among"]],
	// ['むこう', ["over there; beyond; the other side"]],
	// ['まんなか', ["middle; center"]],
	// ['そば', ["near; beside; close to"]],
	// ['まわり', ["around; surrounding; vicinity"]],
	// ['むかい', ["opposite; across from"]],
]

// Vocab lists:
// https://en.wiktionary.org/wiki/Appendix:1000_Japanese_basic_words
// https://thejapanesepage.com/jlpt-n5-vocabulary/
// https://jlptsensei.com/jlpt-n5-vocabulary-list/
const JLPT5Vocabulary = new AnswerKey<string, TimedValue<WordTranslation>>(([
	...prepositions,
	// ['え', ["picture"]],
	// ['ご', ["five; 5"]],
	// ['は', ["tooth"]],
	// ['き', ["tree; shrub; bush; wood; timber"]],
	// ['め', ["eye"]],
	// ['に', ["two; 2"]],
	// ['せ', ["height; stature; back; spine"]],
	// ['し', ["four; 4"]],
	['て', ["hand; arm"]],
	// ['と', ["Japanese style door"]],
	// ['あか', ["red; crimson; scarlet"]],
	// ['あき', ["autumn; fall"]],
	// ['あく', ["to open (e.g. doors, business, etc)"]],
	// ['あめ', ["rain"]],
	// ['あめ', ["candy"]],
	// ['あね', ["older sister; elder sister"]],
	// ['あに', ["elder brother; older brother"]],
	// ['あの', ["that"]],
	// ['あお', ["blue; azure"]],
	// ['あれ', ["that"]],
	['ある', ["to be, to have"]],
	// ['あさ', ["morning"]],
	// ['あし', ["foot; leg; paw; arm"]],
	// ['あと', ["behind; after; remainder; left; also"]],
	// ['あう', ["to meet; to encounter; to see"]],
	// ['バス', ["bus"]],
	// ['ちち', ["father"]],
	// ['ちず', ["map"]],
	// ['だれ', ["who"]],
	// ['だす', ["to take out; to get out; to put out; to reveal"]],
	// ['でる', ["to leave; to exit; to appear; to go out"]],
	// ['ドア', ["door"]],
	// ['どこ', ["where; what place"]],
	// ['どの', ["which [noun or noun phrase]"]],
	// ['どれ', ["which [pronoun] (of three or more)"]],
	// ['どう', ["how; in what way; how about"]],
	// ['ええ', ["yes; that is correct; right"]],
	// ['えき', ["station"]],
	// ['ふく', ["clothes"]],
	// ['ふく', ["to blow (of the wind)"]],
	// ['ふる', ["to fall"]],
	// ['ふゆ', ["winter"]],
	// ['ごご', ["afternoon; p.m."]],
	// ['はち', ["eight: 8"]],
	// ['はは', ["mother"]],
	// ['はい', ["yes; that is correct"]],
	// ['はこ', ["box; crate"]],
	// ['はく', ["to wear, to put on trousers"]],
	// ['はん', ["half; semi-; half-past"]],
	// ['はな', ["flower"]],
	// ['はな', ["nose"]],
	// ['はれ', ["clear weather"]],
	// ['はる', ["spring; springtime"]],
	// ['はる', ["to stick; to paste"]],
	// ['はし', ["chopsticks"]],
	// ['はし', ["bridge"]],
	// ['へん', ["area"]],
	// ['へた', ["unskillful; poor; awkward"]],
	// ['へや', ["room"]],
	// ['ひく', ["to pull"]],
	// ['ひく', ["to play"]],
	// ['ひま', ["free time"]],
	// ['ひる', ["noon; midday; daytime; lunch"]],
	// ['ひと', ["person; human"]],
	// ['ほか', ["other (place, thing, person); the rest"]],
	// ['ほん', ["book; volume; script"]],
	// ['いち', ["one; best; first; foremost; start"]],
	// ['いえ', ["house, residence, family"]],
	// ['いけ', ["pond"]],
	['いく', ["to go; to move"]],
	// ['いま', ["now; the present time; soon"]],
	// ['いみ', ["meaning; significance; sense"]],
	// ['いぬ', ["dog"]],
	// ['いろ', ["color"]],
	// ['いる', ["to be needed"]],
	['いる', ["to be, to have"]],
	// ['いす', ["chair"]],
	// ['いつ', ["when"]],
	// ['いう', ["to say; to call"]],
	// ['いや', ["unpleasant"]],
	// ['かど', ["a corner; angle"]],
	// ['かぎ', ["key"]],
	// ['かく', ["to write; to compose; to pen; to draw"]],
	// ['かみ', ["paper"]],
	// ['かさ', ["umbrella"]],
	// ['かす', ["to lend; to loan"]],
	// ['かた', ["way of doing something"]],
	// ['かう', ["to buy; to purchase"]],
	// ['かわ', ["river; stream"]],
	// ['かぜ', ["wind"]],
	// ['かぜ', ["a cold/illness"]],
	// ['けさ', ["this morning"]],
	// ['けす', ["to erase, to turn off power"]],
	// ['きく', ["to hear; to listen (to music); to ask; to learn of"]],
	// ['きる', ["to cut"]],
	// ['きる', ["to wear"]],
	// ['きた', ["north"]],
	// ['こえ', ["voice"]],
	// ['ここ', ["here; this place"]],
	// ['この', ["this"]],
	// ['これ', ["this"]],
	// ['くち', ["mouth, opening"]],
	// ['くに', ["country; state; region"]],
	// ['くろ', ["black"]],
	['くる', ["to come"]],
	// ['くつ', ["shoes"]],
	// ['まち', ["town; block; neighborhood"]],
	// ['まど', ["window"]],
	// ['まえ', ["previous; before; in front; ago"]],
	// ['まん', ["10,000; ten thousand"]],
	// ['まつ', ["to wait"]],
	// ['みち', ["road; street"]],
	// ['みぎ', ["right; right hand side"]],
	// ['みみ', ["ear; hearing"]],
	['みる', ["to see; to look; to watch; to view; to observe"]],
	// ['みせ', ["store; shop; establishment; restaurant"]],
	// ['みず', ["water; fluid; liquid"]],
	// ['もん', ["gate"]],
	// ['もの', ["thing"]],
	// ['もつ', ["to hold"]],
	// ['むら', ["village"]],
	// ['なか', ["inside; in; within; center"]],
	// ['なく', ["animal noise. to chirp"]],
	// ['なに', ["what"]],
	// ['なつ', ["summer"]],
	// ['なぜ', ["why; how"]],
	// ['ねこ', ["cat"]],
	// ['ねる', ["to sleep; to go to bed; to lie down"]],
	// ['にく', ["meat"]],
	// ['にし', ["west"]],
	// ['にわ', ["garden"]],
	// ['のむ', ["to drink"]],
	// ['のる', ["to get on (train, plane, bus, ship, etc.)"]],
	// ['ぬぐ', ["to take off clothes"]],
	// ['おく', ["to put; to place"]],
	// ['おす', ["to push; to press"]],
	// ['パン', ["bread"]],
	// ['ペン', ["pen"]],
	// ['れい', ["zero"]],
	// ['ろく', ["six; 6"]],
	// ['さあ', ["well…"]],
	// ['さき', ["previous; prior; first; earlier"]],
	// ['さく', ["to bloom"]],
	// ['さん', ["three; 3"]],
	// ['さす', ["to stretch out hands, to raise an umbrella"]],
	// ['せん', ["1,000; thousand"]],
	// ['しち', ["seven; 7"]],
	// ['しぬ', ["to die"]],
	// ['しお', ["salt"]],
	// ['しろ', ["white; innocence; innocent person"]],
	// ['しる', ["to know"]],
	// ['した', ["below; down; under; bottom"]],
	// ['そば', ["near; beside"]],
	// ['そこ', ["that place; there"]],
	// ['その', ["that"]],
	// ['そら', ["sky; the air"]],
	// ['それ', ["that"]],
	// ['そと', ["outside; exterior;"]],
	// ['すき', ["like; favor; prefer; enjoy"]],
	// ['すむ', ["to live in; to reside; to inhabit; to dwell; to abide"]],
	// ['すう', ["to smoke, to suck"]],
	// ['たて', ["length, height"]],
	// ['たつ', ["to stand; to stand up"]],
	// ['とぶ', ["to fly; to hop"]],
	// ['とき', ["time; moment; occasion; chance"]],
	// ['とり', ["bird"]],
	// ['とる', ["to take; to pick up; to harvest; to earn; to win; to choose"]],
	// ['とる', ["to take a photo or record a film"]],
	// ['とし', ["year; age"]],
	// ['つぎ', ["next"]],
	// ['つく', ["to arrive at"]],
	// ['うえ', ["above; up; over; top; surface"]],
	// ['うみ', ["sea"]],
	// ['うる', ["to sell"]],
	// ['うた', ["song"]],
	// ['やま', ["mountain; hill"]],
	// ['やる', ["to do"]],
	// ['よぶ', ["to call out, to invite"]],
	// ['よこ', ["beside, side, width"]],
	// ['よく', ["often, well"]],
	// ['よむ', ["to read; to guess; to predict; to read (someone's thoughts)"]],
	// ['よる', ["evening; night"]],
	// ['よつ', ["four; 4"]],
	// ['ゆき', ["snow"]],
	// ['ゼロ', ["zero"]],
	// ['あびる', ["to bathe, to shower"]],
	// ['あっち', ["over there"]],
	// ['あちら', ["there"]],
	// ['あげる', ["to raise; to elevate; to give"]],
	// ['あかい', ["red; crimson; scarlet"]],
	// ['あける', ["to open (a door, etc.); to unwrap (e.g. parcel, package); to unlock"]],
	// ['あまい', ["sweet; sweet-tasting; sugary; naive; indulgent"]],
	// ['あなた', ["you"]],
	// ['あおい', ["blue; azure"]],
	// ['あらう', ["to wash"]],
	// ['あるく', ["to walk"]],
	// ['あした', ["tomorrow"]],
	// ['あそぶ', ["to play; to enjoy oneself"]],
	// ['あそこ', ["over there"]],
	// ['あたま', ["head"]],
	// ['あつい', ["hot; sultry"]],
	// ['あつい', ["thick"]],
	// ['あつい', ["hot"]],
	// ['バター', ["butter"]],
	// ['ベッド', ["bed"]],
	// ['べんり', ["convenient; handy; useful"]],
	// ['ボタン', ["button"]],
	// ['ぼうし', ["hat; cap"]],
	// ['ちがう', ["to differ"]],
	// ['ちかい', ["near; close"]],
	// ['だれか', ["someone; somebody"]],
	// ['でぐち', ["exit; gateway; way out"]],
	// ['でんき', ["electricity"]],
	// ['でんわ', ["telephone (call / device)l; phone call"]],
	// ['どっち', ["which; which one"]],
	// ['どちら', ["which of two"]],
	// ['どなた', ["who"]],
	// ['どうも', ["thank you; thanks"]],
	// ['どうぞ', ["please"]],
	// ['えいが', ["movie; film"]],
	// ['えいご', ["English language"]],
	// ['ふるい', ["old (not used for people)"]],
	// ['ふたり', ["two people; pair; couple"]],
	// ['ふたつ', ["two; 2"]],
	// ['ふとい', ["fat; thick"]],
	// ['ふつか', ["the second day of the month / 2 days"]],
	// ['げんき', ["lively; full of spirit; energetic; healthy"]],
	// ['ギター', ["guitar"]],
	// ['ごはん', ["cooked rice, meal"]],
	// ['ごぜん', ["morning; a.m."]],
	// ['グラム', ["gram"]],
	// ['はがき', ["postcard"]],
	// ['はいる', ["to enter; to go into"]],
	// ['はなし', ["talk; speech; chat; conversation"]],
	// ['はなす', ["to speak; to talk; to converse"]],
	// ['はれる', ["to be sunny"]],
	// ['はしる', ["to run"]],
	// ['はたち', ["20 years old; twenty years old"]],
	// ['はつか', ["twentieth day of the month / 20 days"]],
	// ['はやい', ["fast; quick; hasty; brisk"]],
	// ['はやい', ["fast; early"]],
	// ['ひだり', ["left; left hand side"]],
	// ['ひがし', ["east"]],
	// ['ひくい', ["short, low"]],
	// ['ひろい', ["spacious; vast; wide"]],
	// ['ひとり', ["one person; alone; single"]],
	// ['ひとつ', ["one thing; only"]],
	// ['ほしい', ["want"]],
	// ['ほそい', ["thin; slender"]],
	// ['ホテル', ["hotel"]],
	// ['ひゃく', ["100; hundred"]],
	// ['いかが', ["how; in what way; how about"]],
	// ['いくら', ["how much?; how many?"]],
	// ['いくつ', ["how many?; how old?"]],
	// ['いれる', ["to put in; to let in; to take in; to bring in; to insert; to install"]],
	// ['いしゃ', ["(medical) doctor; physician"]],
	// ['いたい', ["painful; sore"]],
	// ['いつか', ["the fifth day of the month / 5 days"]],
	// ['いつつ', ["five; 5"]],
	// ['じゃあ', ["then; well; so; well then"]],
	// ['じびき', ["dictionary"]],
	// ['じぶん', ["myself; yourself; oneself; himself; herself; i; me"]],
	// ['じかん', ["time; hour(s)"]],
	// ['じしょ', ["dictionary"]],
	// ['じゅう', ["ten; 10"]],
	// ['かばん', ["bag; basket"]],
	// ['かびん', ["a vase"]],
	// ['かえる', ["to go back"]],
	// ['かえす', ["to return something"]],
	// ['かかる', ["to take (a resource, e.g. time or money)"]],
	// ['かける', ["to hang up; to make (a call);"]],
	// ['カメラ', ["camera"]],
	// ['かんじ', ["kanji"]],
	// ['カップ', ["cup"]],
	// ['からだ', ["body"]],
	// ['からい', ["spicy"]],
	// ['カレー', ["curry"]],
	// ['かりる', ["to borrow"]],
	// ['かるい', ["light"]],
	// ['かてい', ["household"]],
	// ['かぞく', ["family; members of a family"]],
	// ['きえる', ["to disappear"]],
	// ['きのう', ["yesterday"]],
	// ['きっぷ', ["ticket"]],
	// ['きらい', ["hate"]],
	// ['きれい', ["pretty; lovely; beautiful"]],
	// ['きって', ["stamp (postage)"]],
	// ['こっち', ["this person or way"]],
	// ['こちら', ["this way; this direction"]],
	// ['こども', ["child"]],
	// ['こまる', ["to be troubled"]],
	// ['こんな', ["such; like this"]],
	// ['コート', ["coat"]],
	// ['コピー', ["copy; photocopy"]],
	// ['コップ', ["glass (drinking vessel); tumbler"]],
	// ['ことば', ["word; words"]],
	// ['ことし', ["this year"]],
	// ['くもり', ["cloudiness; cloudy weather"]],
	// ['くもる', ["to become cloudy, to become dim"]],
	// ['くらい', ["dark; gloomy; murky"]],
	// ['クラス', ["class"]],
	// ['くろい', ["black"]],
	// ['くるま', ["car; automobile; vehicle"]],
	// ['くすり', ["medicine"]],
	// ['きょう', ["today; this day"]],
	// ['きゅう', ["nine; 9"]],
	// ['マッチ', ["match"]],
	// ['まがる', ["to turn, to bend"]],
	// ['まるい', ["round, circular"]],
	// ['まずい', ["unpleasant"]],
	// ['めがね', ["glasses"]],
	// ['みどり', ["green"]],
	// ['みがく', ["to polish; to shine; to brush (e.g. teeth)"]],
	// ['みっか', ["the third day of the month / 3 days"]],
	// ['みなみ', ["south"]],
	// ['みんな', ["all; everyone; everybody"]],
	// ['みせる', ["to show; to display"]],
	// ['みっつ', ["three; 3"]],
	// ['もっと', ["more; longer; further"]],
	// ['むいか', ["sixth day of the month / 6 days"]],
	// ['むこう', ["over there"]],
	// ['むっつ', ["six; 6"]],
	// ['ながい', ["long (distance); long (time); lengthy."]],
	// ['ナイフ', ["knife"]],
	// ['なくす', ["to lose (something)"]],
	// ['なまえ', ["name; full name; given name"]],
	// ['ななつ', ["seven; 7"]],
	// ['なのか', ["seventh day of the month / 7 days"]],
	// ['ならぶ', ["to line up, to stand in a line"]],
	// ['ならう', ["to be taught; to learn (from a teacher)"]],
	// ['にっき', ["diary; journal"]],
	// ['にもつ', ["luggage; baggage"]],
	// ['のぼる', ["to climb"]],
	// ['ノート', ["notebook"]],
	// ['ぬるい', ["luke warm"]],
	// ['おちゃ', ["tea"]],
	// ['おふろ', ["bath"]],
	// ['おかね', ["money"]],
	// ['おかし', ["confections; sweets; candy"]],
	// ['おきる', ["to get up; to wake up"]],
	// ['おもい', ["heavy"]],
	// ['おなじ', ["same"]],
	// ['おなか', ["stomach"]],
	// ['おんな', ["woman; female sex"]],
	// ['おおい', ["many; numerous; a lot; large quantity; frequent"]],
	// ['おりる', ["to get off"]],
	// ['おさけ', ["alcohol"]],
	// ['おさら', ["plate, dish"]],
	// ['おそい', ["slow; time-consuming; late"]],
	// ['おとこ', ["man; male"]],
	// ['おとな', ["adult"]],
	// ['おわる', ["to finish; to end"]],
	// ['およぐ', ["to swim"]],
	// ['ページ', ["page"]],
	// ['ペット', ["pet"]],
	// ['ポスト', ["post"]],
	// ['プール', ["swimming pool"]],
	// ['ラジオ', ["radio"]],
	// ['りっぱ', ["splendid"]],
	// ['ろうか', ["corridor; hallway; passageway"]],
	// ['さいふ', ["purse; wallet"]],
	// ['さかな', ["fish"]],
	// ['さむい', ["cold"]],
	// ['さんぽ', ["walk; stroll"]],
	// ['さとう', ["sugar"]],
	// ['せびろ', ["business suit"]],
	// ['せいと', ["pupil; student"]],
	// ['せまい', ["narrow"]],
	// ['シャツ', ["shirt"]],
	// ['しごと', ["work; job; business"]],
	// ['しまる', ["to close, to be closed"]],
	// ['しめる', ["to close; to shut"]],
	// ['しめる', ["to tie; to fasten; to tighten"]],
	// ['しろい', ["white"]],
	// ['しずか', ["quiet"]],
	// ['そっち', ["that way; over there"]],
	// ['そちら', ["that way (distant from speaker, close to listener); you; your family"]],
	// ['そうじ', ["to clean, to sweep"]],
	// ['すこし', ["a little (bit); small quantity; few; short distance"]],
	// ['すわる', ["to sit"]],
	// ['たばこ', ["tobacco; cigarette"]],
	// ['たべる', ["to eat"]],
	// ['たぶん', ["perhaps; probably"]],
	// ['たかい', ["high; tall; expensive; above average"]],
	// ['たまご', ["eggs; egg"]],
	// ['たのむ', ["to ask"]],
	// ['テープ', ["tape"]],
	// ['てがみ', ["Letter (message)"]],
	// ['てんき', ["weather; the elements"]],
	// ['テレビ', ["television; TV"]],
	// ['テスト', ["examination; quiz; test"]],
	// ['トイレ', ["toilet"]],
	// ['とけい', ["watch; clock; timepiece"]],
	// ['ところ', ["place"]],
	// ['とまる', ["to stop; to come to a halt"]],
	// ['となり', ["next door to"]],
	// ['とおい', ["far"]],
	// ['とおか', ["tenth day of the month / 10 days"]],
	// ['つかう', ["to use"]],
	// ['つける', ["to turn on"]],
	// ['つける', ["to attach; affix; add; apply"]],
	// ['つくえ', ["desk"]],
	// ['つくる', ["to make"]],
	// ['つよい', ["powerful"]],
	// ['うしろ', ["back; behind; rear"]],
	// ['うすい', ["thin; weak"]],
	// ['うたう', ["to sing"]],
	// ['うわぎ', ["coat; tunic; jacket; outer garment"]],
	// ['わかい', ["young"]],
	['わかる', ["to understand; to comprehend; to grasp; to see; to get; to follow"]],
	// ['わるい', ["bad; poor; undesirable"]],
	// ['わたる', ["to go across"]],
	// ['わたし', ["I; myself"]],
	// ['わたす', ["to hand over"]],
	// ['やおや', ["greengrocer; fruit and vegetable shop; versatile"]],
	// ['やさい', ["vegetable"]],
	// ['やすい', ["cheap; inexpensive"]],
	// ['やすみ', ["rest; vacation; holiday"]],
	// ['やすむ', ["to be absent; to take a day off; to rest"]],
	// ['やっつ', ["eight: 8"]],
	// ['よっか', ["fourth day of the month / 4 days"]],
	// ['ようか', ["eighth day of the month / 8 days"]],
	// ['よわい', ["weak"]],
	// ['ゆうべ', ["last night"]],
	// ['ざっし', ["magazine"]],
	// ['ぜんぶ', ["all"]],
	// ['ズボン', ["trousers; pants"]],
	// ['すぐに', ["immediately; right away; instantly"]],
	// ['あぶない', ["dangerous"]],
	// ['あかるい', ["bright; light"]],
	// ['アパート', ["apartment"]],
	// ['あさって', ["day after tomorrow"]],
	// ['ばんごう', ["number"]],
	// ['ぶたにく', ["pork"]],
	// ['びょうき', ["illness; disease; sickness"]],
	// ['ちゃいろ', ["brown"]],
	// ['ちゃわん', ["rice bowl; tea cup; teacup"]],
	// ['ちいさい', ["small; little; tiny"]],
	// ['ちいさな', ["small; little; tiny"]],
	// ['ちかてつ', ["subway; underground train"]],
	// ['ちょっと', ["a little"]],
	// ['ちょうど', ["exactly"]],
	// ['だいがく', ["university; college"]],
	// ['だいすき', ["love; like; like very much"]],
	// ['だんだん', ["gradually"]],
	// ['でかける', ["to go out; to leave; to depart"]],
	// ['でんしゃ', ["train; electric train"]],
	// ['デパート', ["department store"]],
	// ['どうぶつ', ["animal"]],
	// ['どようび', ["Saturday"]],
	// ['えんぴつ', ["pencil"]],
	// ['フィルム', ["film"]],
	// ['フォーク', ["fork"]],
	// ['ふうとう', ["envelope"]],
	// ['がいこく', ["foreign country"]],
	// ['がっこう', ["school"]],
	// ['がくせい', ["student"]],
	// ['げんかん', ["entrance"]],
	// ['ぎんこう', ["bank"]],
	// ['はいざら', ["ashtray"]],
	// ['はじまる', ["to begin"]],
	// ['はじめて', ["for the first time"]],
	// ['はんぶん', ["half"]],
	// ['ハンカチ', ["handkerchief"]],
	// ['はたらく', ["to work"]],
	// ['ひこうき', ["airplane; aircraft"]],
	// ['ほんだな', ["bookshelf; bookcase"]],
	// ['ほんとう', ["truth; reality; actuality; fact"]],
	// ['いちばん', ["number one; first; 1st, first place; best; most"]],
	// ['いちにち', ["one day, all day"]],
	// ['いもうと', ["younger sister"]],
	// ['いりぐち', ["entrance; entry; gate"]],
	// ['いろいろ', ["various"]],
	// ['いっしょ', ["together; at the same time; same; identical"]],
	// ['じょうぶ', ["strong, durable"]],
	// ['じょうず', ["skillful; skilled; proficient; good (at)"]],
	// ['かいだん', ["stairs; stairway; staircase"]],
	// ['かいもの', ["shopping; purchased goods"]],
	// ['かいしゃ', ["company; corporation"]],
	// ['かわいい', ["cute"]],
	// ['かようび', ["Tuesday"]],
	// ['けいかん', ["policeman; police officer"]],
	// ['けっこん', ["marriage"]],
	// ['けっこう', ["splendid, enough"]],
	// ['きいろい', ["yellow"]],
	// ['きたない', ["dirty"]],
	// ['ここのか', ["ninth day of the month / 9 days"]],
	// ['ここのつ', ["nine; 9"]],
	// ['こんばん', ["tonight; this evening"]],
	// ['こんげつ', ["this month"]],
	// ['コーヒー', ["Coffee"]],
	// ['こたえる', ["to answer"]],
	// ['こうばん', ["police box"]],
	// ['こうちゃ', ["black tea"]],
	// ['こうえん', ["park"]],
	// ['くだもの', ["fruit"]],
	// ['ください', ["please"]],
	// ['くつした', ["socks"]],
	// ['きょねん', ["last year"]],
	// ['まいあさ', ["every morning"]],
	// ['まいばん', ["every night"]],
	// ['まいにち', ["every day"]],
	// ['まいつき', ["every month; monthly"]],
	// ['まっすぐ', ["straight ahead, direct"]],
	// ['メートル', ["metre; meter"]],
	// ['みじかい', ["short"]],
	// ['みなさん', ["everyone"]],
	// ['もんだい', ["problem; question (e.g. on a test)"]],
	// ['ならべる', ["to line up, to set up"]],
	// ['ネクタイ', ["tie; necktie"]],
	// ['にぎやか', ["bustling, busy"]],
	// ['のみもの', ["drink; beverage"]],
	// ['ニュース', ["news"]],
	// ['おばさん', ["aunt; old lady"]],
	// ['おぼえる', ["to remember"]],
	// ['おいしい', ["delicious"]],
	// ['おじさん', ["uncle; old man; mister"]],
	// ['おくさん', ["wife; your wife; his wife"]],
	// ['おんがく', ["music"]],
	// ['おおきい', ["big; large; great; important"]],
	// ['おおきな', ["big; large; great"]],
	// ['おおぜい', ["crowd of people; great number of people"]],
	// ['おしえる', ["to teach"]],
	// ['おととい', ["day before yesterday"]],
	// ['おととし', ["year before last"]],
	// ['おとうと', ["younger brother"]],
	// ['ポケット', ["pocket"]],
	// ['らいげつ', ["next month"]],
	// ['らいねん', ["next year"]],
	// ['レコード', ["record"]],
	// ['りょこう', ["travel; trip; journey; excursion; tour"]],
	// ['りょうり', ["cuisine"]],
	// ['さくぶん', ["writing; composition"]],
	// ['セーター', ["sweater; jumper"]],
	// ['せっけん', ["soap"]],
	// ['せんげつ', ["last month"]],
	// ['せんせい', ["teacher; instructor; master"]],
	// ['せんたく', ["washing; laundry"]],
	// ['しゃしん', ["photograph; photo"]],
	// ['シャワー', ["shower"]],
	// ['しんぶん', ["newspaper"]],
	// ['しつもん', ["question; inquiry"]],
	// ['しょうゆ', ["soy sauce"]],
	// ['それでは', ["in that situation"]],
	// ['スカート', ["skirt"]],
	// ['すくない', ["few; a little; scarce; insufficient; seldom"]],
	// ['スポーツ', ["sport; sports"]],
	// ['スプーン', ["spoon"]],
	// ['スリッパ', ["slipper; slippers"]],
	// ['ストーブ', ["heater; stove"]],
	// ['すずしい', ["refreshing, cool"]],
	// ['たべもの', ["food"]],
	// ['たいへん', ["very; greatly; terribly; serious; difficult"]],
	// ['たいせつ', ["important; necessary; indispensable; beloved"]],
	// ['たくさん', ["many"]],
	// ['タクシー', ["taxi"]],
	// ['たのしい', ["enjoyable; fun"]],
	// ['たてもの', ["building"]],
	// ['テーブル', ["table"]],
	// ['ときどき', ["sometimes; at times"]],
	// ['ともだち', ["friend; companion"]],
	// ['とりにく', ["chicken meat"]],
	// ['ついたち', ["first day of the month"]],
	// ['つかれる', ["to get tired"]],
	// ['つめたい', ["cold to the touch"]],
	// ['つとめる', ["to work for someone"]],
	// ['うまれる', ["to be born"]],
	// ['うるさい', ["noisy, annoying"]],
	// ['わすれる', ["to forget"]],
	// ['やさしい', ["easy, simple"]],
	// ['ようふく', ["western clothes"]],
	// ['ゆっくり', ["slowly"]],
	// ['ゆうがた', ["evening; dusk"]],
	// ['ゆうはん', ["evening meal"]],
	// ['ゆうめい', ["famous"]],
	// ['あさごはん', ["breakfast"]],
	// ['あたらしい', ["new; novel; fresh; recent; latest"]],
	// ['あたたかい', ["warm"]],
	// ['ばんごはん', ["dinner; evening meal"]],
	// ['べんきょう', ["to study"]],
	// ['ボールペン', ["ball-point pen"]],
	// ['ぶんしょう', ["sentence"]],
	// ['びょういん', ["hospital"]],
	// ['だいどころ', ["kitchen"]],
	// ['えいがかん', ["movie theater; cinema"]],
	// ['げつようび', ["Monday"]],
	// ['ぎゅうにく', ["beef"]],
	// ['ひるごはん', ["lunch"]],
	// ['いそがしい', ["busy"]],
	// ['じどうしゃ', ["automobile; motorcar; motor vehicle; car"]],
	// ['じてんしゃ', ["bicycle"]],
	// ['じゅぎょう', ["lesson; class work"]],
	// ['カレンダー', ["calendar"]],
	// ['きんようび', ["Friday"]],
	// ['キログラム', ["kilogram"]],
	// ['きっさてん', ["coffee shop; tearoom; cafe"]],
	// ['こんしゅう', ["this week"]],
	// ['こうさてん', ["intersection"]],
	// ['きょうだい', ["siblings; brothers and sisters; mate"]],
	// ['きょうしつ', ["classroom"]],
	// ['まいしゅう', ["every week"]],
	// ['もくようび', ["Thursday"]],
	// ['もういちど', ["once more; again"]],
	// ['むずかしい', ["difficult"]],
	// ['なつやすみ', ["summer vacation; summer holiday"]],
	// ['にちようび', ["Sunday"]],
	// ['おばあさん', ["grandmother"]],
	// ['おべんとう', ["lunch box; Japanese box lunch"]],
	// ['おかあさん', ["mother; mom; mum; ma"]],
	// ['おもしろい', ["interesting"]],
	// ['おねえさん', ["elder sister; young lady; miss; ma'am"]],
	// ['おにいさん', ["older brother; elder brother; young man; buddy"]],
	// ['おんなのこ', ["girl; daughter; young women"]],
	// ['おてあらい', ["toilet; restroom; lavatory; bathroom"]],
	// ['おとこのこ', ["boy; male child; baby boy"]],
	// ['おとうさん', ["father; dad; papa; pa; pop; daddy"]],
	// ['パーティー', ["party"]],
	// ['らいしゅう', ["next week"]],
	// ['れいぞうこ', ["refrigerator"]],
	// ['れんしゅう', ["practice; practicing"]],
	// ['レストラン', ["restaurant"]],
	// ['りょうしん', ["parents; both parents"]],
	// ['さらいねん', ["year after next"]],
	// ['せんしゅう', ["last week"]],
	// ['しょくどう', ["cafeteria; dining room"]],
	// ['しゅくだい', ["homework; assignment; pending issue"]],
	// ['すいようび', ["Wednesday"]],
	// ['たいしかん', ["embassy"]],
	// ['としょかん', ["library"]],
	// ['つまらない', ["boring"]],
	// ['ワイシャツ', ["shirt"]],
	// ['だいじょうぶ', ["OK; okay; alright; problem free"]],
	// ['エレベーター', ["elevator"]],
	// ['がいこくじん', ["foreigner; foreign citizen; foreign national; alien; non-Japanese"]],
	// ['ぎゅうにゅう', ["(cow's) milk"]],
	// ['キロメートル', ["kilometer"]],
	// ['まんねんひつ', ["fountain pen"]],
	// ['たんじょうび', ["birthday"]],
	// ['よい / いい', ["good"]],
	// ['おまわりさん', ["police officer (friendly term for policeman)"]],
	// ['りゅうがくせい', ["overseas student; exchange student"]],
	// ['ゆうびんきょく', ["post office"]],
	// ['テープレコーダー', ["tape recorder"]],
	// ['まいとし / まいねん', ["every year; yearly; annually"]],
] as [string, WordTranslation][])
	.map(([question, answer]) =>
		[question, { value: answer, timeSeconds: timeLimitSeconds }]
	))

// Old/original answer key
// const answer_key = new Map<string, TimedValue<WordTranslation>>(([
// 	['あめ', ['Rain', 'Candy']],
// 	['あと', ['Behind', 'After', 'Remainder', 'Left', 'Also']],
// 	// ['はい', ['Yes']],
// 	// ['あい', ['Love']],
// 	// ['はな', ['Flower']],
// 	// ['いす', ['Chair']],
// 	// ['かみ', ['Paper']],
// 	// ["うた", ['Song']],
// 	// ['くち', ['Mouth', 'Opening']],
// 	// ['くろ', ['Black']],
// 	// ['あか', ['Red']],
// 	// ['あお', ['Blue']],
// 	// ['しろ', ['White']],
// 	// ['みず', ['Water']],
// 	// ['ちず', ['Map']],
// 	// ['つき', ['Moon']],
// 	// ['みみ', ['Ear']],
// 	// ['ほん', ['Book']],
// 	// ['ねこ', ['Cat']],
// 	// ['いぬ', ['Dog']],
// 	// ['へび', ['Snake']],
// 	['うま', ['Horse']],
// 	['くま', ['Bear']],
// 	// ['やま', ['Mountain']],
// 	// ["いけ", ['Pond']],
// 	["うみ", ['Sea', 'Ocean']],
// 	// ['そら', ['Sky']],
// 	['くも', ['Cloud', 'Spider']],
// 	// ['あき', ['Autumn', 'Fall']],
// 	// ['くつ', ['Shoes', 'Footwear']],
// 	// ['ちゃ', ['Tea']],
// 	['むし', ['Insect', 'Bug']],
// 	// ['あさ', ['Morning']],
// 	// ['いえ', ['House']],
// 	// ['あし', ['Foot', 'Leg']],
// 	// ['あに', ['Older brother']],
// 	// ['あね', ['Older sister']],
// 	['あれ/あの', ['That (over there)', 'That (mutually familiar thing)']],
// 	['これ/この', ['This (near me)']],
// 	['それ/その', ['That (near you)']],
// 	['どの', ['Which (one, of at least three)']],
// 	// Three characters
// 	// ["あたま", ['Head']],
// 	// ['あまい', ['Sweet']],
// 	// ['あなた', ['You']],
// 	// ["あつい", ['Thick', 'Hot']],
// 	// ["いしゃ", ['Doctor']],
// 	["いたい", ['Painful', 'Hurt']],
// 	["いつも", ['Always']],
// 	["うしろ", ['Back', 'Behind']],
// 	["うすい", ['Thin', 'Weak']],
// 	["うわぎ", ['Jacket']],
// 	// ["えいが", ['Movie']],
// 	// ["おかね", ['Money']],
// 	// ['いいえ', ['No']],
// 	['あした', ['Tomorrow']],
// 	// Four characters
// 	["おいしい", ['Delicious']],
// 	['あかるい', ['Bright']],
// 	['アパート', ['Apartment']],
// 	["あさって", ['Day after tomorrow']],
// 	// Five characters
// 	// ['あたらしい', ['New']],
// 	// ['おてあらい', ['Bathroom', 'Restroom']],
// 	// ["いそがしい", ['Busy']],
// 	// ["あさごはん", ['Breakfast']],
// 	// ["ばんごはん", ['Dinner']],
// ] as [string, WordTranslation][])
// 	.map(([question, answer]) =>
// 		[question, { value: answer, timeSeconds: timeLimitSeconds }]
// 	))

export const japaneseToEnglishVocabulary = new QuizBuilder<
	string, // QuestionType
	TimedValue<WordTranslation>, // AnswerType
	TimedValue<WordTranslation>, // ResponseType
	string // FeedbackType
>({
	title: "Japanese to English Vocabulary",
	answerKey: JLPT5Vocabulary,
	coordinator: new DefaultCoordinator({
		evaluator: (response, answer) => floatTimedCompareStrictlyEqual<string>(
			// Flatten the arrays
			{ value: response.value.join('; '), timeSeconds: response.timeSeconds },
			{ value: answer.value.join('; '), timeSeconds: answer.timeSeconds }
		),
		feedback: {
			correct: () => "Correct!",
			tryAgain: (parameters) => `Hint: ${parameters.answer.value[0][0]}`,
			fail: (parameters) => `${parameters.question} means "${parameters.answer.value}"`
		}
	}),
	layout: DefaultQuizLayoutBuilder<
		string,
		TimedValue<WordTranslation>,
		TimedValue<WordTranslation>,
		string
	>({
		responseFetcher: (props) => <AutofillEnumFetcher {...props} possibleResponses={
			new Set(props.answerKey.values().map(timedValue => timedValue.value[0]))
		} />,
		questionRenderer: (props) => <TextRenderer prompt={"What does this word mean:"} {...props} />,
	}),
})

export const englishToJapaneseVocabulary = new QuizBuilder<
	string, // QuestionType
	TimedValue<string>, // AnswerType
	TimedValue<string>, // ResponseType
	string // FeedbackType
>({
	title: "English to Japanese Vocabulary",
	answerKey: new AnswerKey(
		JLPT5Vocabulary.entries().toArray().map(([question, { value: answer, timeSeconds }]) =>
			[answer.join('; '), { value: question, timeSeconds }]
		)
	),
	coordinator: new DefaultCoordinator({
		evaluator: floatTimedCompareStrictlyEqual<string>,
		feedback: {
			correct: () => "Correct!",
			tryAgain: (parameters) => `Hint: ${parameters.answer.value[0]}`,
			fail: (parameters) => `${parameters.answer.value} means "${parameters.question}"`
		}
	}),
	layout: DefaultQuizLayoutBuilder<
		string,
		TimedValue<string>,
		TimedValue<string>,
		string
	>({
		responseFetcher: (props) => <MultipleChoiceFetcher
			incorrectOptionsCount={new NonNegativeNumber(8)}
			getLabel={(option) => option.value}
			{...props}
		/>,
		questionRenderer: (props) => <TextRenderer prompt={"What is the Japanese word for:"} {...props} />,
	}),
	backgroundImage: await getRandomPhoto("japanese")
})
