/*
enum MoraOption {
	a,
	i,
	u,
	e,
	o,
	ka,
	ki,
	ku,
	ke,
	ko,
	ga,
	gi,
	gu,
	ge,
	go,
	sa,
	shi,
	su,
	se,
	so,
	za,
	ji,
	zu,
	ze,
	zo,
	ta,
	chi,
	tsu,
	te,
	to,
	da,
	// ji,
	// zu,
	de,
	do,
	na,
	ni,
	nu,
	ne,
	no,
	ha,
	hi,
	fu,
	he,
	ho,
	ba,
	bi,
	bu,
	be,
	bo,
	pa,
	pi,
	pu,
	pe,
	po,
	ma,
	mi,
	mu,
	me,
	mo,
	ya,
	yu,
	yo,
	ra,
	ri,
	ru,
	re,
	ro,
	wa,
	wi,
	we,
	wo,
	n,
}

type Instances<T extends MoraOption> = { [t in T]: {
	hiragana: string
	katakana: string
	romanization: string
	ipa: string
}
}

class _Mora {
	private readonly instances: Instances<MoraOption> = {
		[MoraOption.a]: { hiragana: 'あ', katakana: 'ア', romanization: 'a', ipa: 'a' },
		[MoraOption.i]: { hiragana: 'い', katakana: 'イ', romanization: 'i', ipa: 'i' },
		[MoraOption.u]: { hiragana: 'う', katakana: 'ウ', romanization: 'u', ipa: 'ɯ' },
		[MoraOption.e]: { hiragana: 'え', katakana: 'エ', romanization: 'e', ipa: 'e' },
		[MoraOption.o]: { hiragana: 'お', katakana: 'オ', romanization: 'o', ipa: 'o' },
		[MoraOption.ka]: { hiragana: 'か', katakana: 'カ', romanization: 'ka', ipa: 'ka' },
		[MoraOption.ki]: { hiragana: 'き', katakana: 'キ', romanization: 'ki', ipa: 'ki' },
		[MoraOption.ku]: { hiragana: 'く', katakana: 'ク', romanization: 'ku', ipa: 'kɯ' },
		[MoraOption.ke]: { hiragana: 'け', katakana: 'ケ', romanization: 'ke', ipa: 'ke' },
		[MoraOption.ko]: { hiragana: 'こ', katakana: 'コ', romanization: 'ko', ipa: 'ko' },
		[MoraOption.ga]: { hiragana: 'が', katakana: 'ガ', romanization: 'ga', ipa: 'ga' },
		[MoraOption.gi]: { hiragana: 'ぎ', katakana: 'ギ', romanization: 'gi', ipa: 'gi' },
		[MoraOption.gu]: { hiragana: 'ぐ', katakana: 'グ', romanization: 'gu', ipa: 'gɯ' },
		[MoraOption.ge]: { hiragana: 'げ', katakana: 'ゲ', romanization: 'ge', ipa: 'ge' },
		[MoraOption.go]: { hiragana: 'ご', katakana: 'ゴ', romanization: 'go', ipa: 'go' },
		[MoraOption.sa]: { hiragana: 'さ', katakana: 'サ', romanization: 'sa', ipa: 'sa' },
		[MoraOption.shi]: { hiragana: 'し', katakana: 'シ', romanization: 'shi', ipa: 'ɕi' },
		[MoraOption.su]: { hiragana: 'す', katakana: 'ス', romanization: 'su', ipa: 'sɯ' },
		[MoraOption.se]: { hiragana: 'せ', katakana: 'セ', romanization: 'se', ipa: 'se' },
		[MoraOption.so]: { hiragana: 'そ', katakana: 'ソ', romanization: 'so', ipa: 'so' },
		[MoraOption.za]: { hiragana: 'ざ', katakana: 'ザ', romanization: 'za', ipa: 'za' },
		[MoraOption.ji]: { hiragana: 'じ', katakana: 'ジ', romanization: 'ji', ipa: 'dʑi' },
		[MoraOption.zu]: { hiragana: 'ず', katakana: 'ズ', romanization: 'zu', ipa: 'zɯ' },
		[MoraOption.ze]: { hiragana: 'ぜ', katakana: 'ゼ', romanization: 'ze', ipa: 'ze' },
		[MoraOption.zo]: { hiragana: 'ぞ', katakana: 'ゾ', romanization: 'zo', ipa: 'zo' },
		[MoraOption.ta]: { hiragana: 'た', katakana: 'タ', romanization: 'ta', ipa: 'ta' },
		[MoraOption.chi]: { hiragana: 'ち', katakana: 'チ', romanization: 'chi', ipa: 'tɕi' },
		[MoraOption.tsu]: { hiragana: 'つ', katakana: 'ツ', romanization: 'tsu', ipa: 'tsɯ' },
		[MoraOption.te]: { hiragana: 'て', katakana: 'テ', romanization: 'te', ipa: 'te' },
		[MoraOption.to]: { hiragana: 'と', katakana: 'ト', romanization: 'to', ipa: 'to' },
		[MoraOption.da]: { hiragana: 'だ', katakana: 'ダ', romanization: 'da', ipa: 'da' },
		[MoraOption.de]: { hiragana: 'で', katakana: 'デ', romanization: 'de', ipa: 'de' },
		[MoraOption.do]: { hiragana: 'ど', katakana: 'ド', romanization: 'do', ipa: 'do' },
		[MoraOption.na]: { hiragana: 'な', katakana: 'ナ', romanization: 'na', ipa: 'na' },
		[MoraOption.ni]: { hiragana: 'に', katakana: 'ニ', romanization: 'ni', ipa: 'ni' },
		[MoraOption.nu]: { hiragana: 'ぬ', katakana: 'ヌ', romanization: 'nu', ipa: 'nɯ' },
		[MoraOption.ne]: { hiragana: 'ね', katakana: 'ネ', romanization: 'ne', ipa: 'ne' },
		[MoraOption.no]: { hiragana: 'の', katakana: 'ノ', romanization: 'no', ipa: 'no' },
		[MoraOption.ha]: { hiragana: 'は', katakana: 'ハ', romanization: 'ha', ipa: 'ha' },
		[MoraOption.hi]: { hiragana: 'ひ', katakana: 'ヒ', romanization: 'hi', ipa: 'hi' },
		[MoraOption.fu]: { hiragana: 'ふ', katakana: 'フ', romanization: 'fu', ipa: 'ɸɯ' },
		[MoraOption.he]: { hiragana: 'へ', katakana: 'ヘ', romanization: 'he', ipa: 'he' },
		[MoraOption.ho]: { hiragana: 'ほ', katakana: 'ホ', romanization: 'ho', ipa: 'ho' },
		[MoraOption.ba]: { hiragana: 'ば', katakana: 'バ', romanization: 'ba', ipa: 'ba' },
		[MoraOption.bi]: { hiragana: 'び', katakana: 'ビ', romanization: 'bi', ipa: 'bi' },
		[MoraOption.bu]: { hiragana: 'ぶ', katakana: 'ブ', romanization: 'bu', ipa: 'bɯ' },
		[MoraOption.be]: { hiragana: 'べ', katakana: 'ベ', romanization: 'be', ipa: 'be' },
		[MoraOption.bo]: { hiragana: 'ぼ', katakana: 'ボ', romanization: 'bo', ipa: 'bo' },
		[MoraOption.pa]: { hiragana: 'ぱ', katakana: 'パ', romanization: 'pa', ipa: 'pa' },
		[MoraOption.pi]: { hiragana: 'ぴ', katakana: 'ピ', romanization: 'pi', ipa: 'pi' },
		[MoraOption.pu]: { hiragana: 'ぷ', katakana: 'プ', romanization: 'pu', ipa: 'pɯ' },
		[MoraOption.pe]: { hiragana: 'ぺ', katakana: 'ペ', romanization: 'pe', ipa: 'pe' },
		[MoraOption.po]: { hiragana: 'ぽ', katakana: 'ポ', romanization: 'po', ipa: 'po' },
		[MoraOption.ma]: { hiragana: 'ま', katakana: 'マ', romanization: 'ma', ipa: 'ma' },
		[MoraOption.mi]: { hiragana: 'み', katakana: 'ミ', romanization: 'mi', ipa: 'mi' },
		[MoraOption.mu]: { hiragana: 'む', katakana: 'ム', romanization: 'mu', ipa: 'mɯ' },
		[MoraOption.me]: { hiragana: 'め', katakana: 'メ', romanization: 'me', ipa: 'me' },
		[MoraOption.mo]: { hiragana: 'も', katakana: 'モ', romanization: 'mo', ipa: 'mo' },
		[MoraOption.ya]: { hiragana: 'や', katakana: 'ヤ', romanization: 'ya', ipa: 'ja' },
		[MoraOption.yu]: { hiragana: 'ゆ', katakana: 'ユ', romanization: 'yu', ipa: 'jɯ' },
		[MoraOption.yo]: { hiragana: 'よ', katakana: 'ヨ', romanization: 'yo', ipa: 'jo' },
		[MoraOption.ra]: { hiragana: 'ら', katakana: 'ラ', romanization: 'ra', ipa: 'ɾa' },
		[MoraOption.ri]: { hiragana: 'り', katakana: 'リ', romanization: 'ri', ipa: 'ɾi' },
		[MoraOption.ru]: { hiragana: 'る', katakana: 'ル', romanization: 'ru', ipa: 'ɾɯ' },
		[MoraOption.re]: { hiragana: 'れ', katakana: 'レ', romanization: 're', ipa: 'ɾe' },
		[MoraOption.ro]: { hiragana: 'ろ', katakana: 'ロ', romanization: 'ro', ipa: 'ɾo' },
		[MoraOption.wa]: { hiragana: 'わ', katakana: 'ワ', romanization: 'wa', ipa: 'wa' },
		[MoraOption.wi]: { hiragana: 'ゐ', katakana: 'ヰ', romanization: 'wi', ipa: 'i' },
		[MoraOption.we]: { hiragana: 'ゑ', katakana: 'ヱ', romanization: 'we', ipa: 'e' },
		[MoraOption.wo]: { hiragana: 'を', katakana: 'ヲ', romanization: 'wo', ipa: 'o' },
		[MoraOption.n]: { hiragana: 'ん', katakana: 'ン', romanization: 'n', ipa: 'n' },
	}

	readonly hiragana: string
	readonly katakana: string
	readonly romanization: string
	readonly ipa: string

	public constructor(private readonly mora: MoraOption) {
		this.hiragana = this.instances[this.mora].hiragana
		this.katakana = this.instances[this.mora].katakana
		this.romanization = this.instances[this.mora].romanization
		this.ipa = this.instances[this.mora].ipa
	}
}
*/

export interface Mora {
	readonly hiragana: string
	readonly katakana: string
	readonly consonant: string
	readonly vowel: string
	readonly romanization: string
	readonly ipa: string
}

export const mora: { readonly [key: string]: Mora } = {
	'a': { hiragana: 'あ', katakana: 'ア', romanization: 'a', ipa: 'a', consonant: '', vowel: 'a' },
	'i': { hiragana: 'い', katakana: 'イ', romanization: 'i', ipa: 'i', consonant: '', vowel: 'i' },
	'u': { hiragana: 'う', katakana: 'ウ', romanization: 'u', ipa: 'ɯ', consonant: '', vowel: 'u' },
	'e': { hiragana: 'え', katakana: 'エ', romanization: 'e', ipa: 'e', consonant: '', vowel: 'e' },
	'o': { hiragana: 'お', katakana: 'オ', romanization: 'o', ipa: 'o', consonant: '', vowel: 'o' },
	'ka': { hiragana: 'か', katakana: 'カ', romanization: 'ka', ipa: 'ka', consonant: 'k', vowel: 'a' },
	'ki': { hiragana: 'き', katakana: 'キ', romanization: 'ki', ipa: 'ki', consonant: 'k', vowel: 'i' },
	'ku': { hiragana: 'く', katakana: 'ク', romanization: 'ku', ipa: 'kɯ', consonant: 'k', vowel: 'u' },
	'ke': { hiragana: 'け', katakana: 'ケ', romanization: 'ke', ipa: 'ke', consonant: 'k', vowel: 'e' },
	'ko': { hiragana: 'こ', katakana: 'コ', romanization: 'ko', ipa: 'ko', consonant: 'k', vowel: 'o' },
	'ga': { hiragana: 'が', katakana: 'ガ', romanization: 'ga', ipa: 'ga', consonant: 'g', vowel: 'a' },
	'gi': { hiragana: 'ぎ', katakana: 'ギ', romanization: 'gi', ipa: 'gi', consonant: 'g', vowel: 'i' },
	'gu': { hiragana: 'ぐ', katakana: 'グ', romanization: 'gu', ipa: 'gɯ', consonant: 'g', vowel: 'u' },
	'ge': { hiragana: 'げ', katakana: 'ゲ', romanization: 'ge', ipa: 'ge', consonant: 'g', vowel: 'e' },
	'go': { hiragana: 'ご', katakana: 'ゴ', romanization: 'go', ipa: 'go', consonant: 'g', vowel: 'o' },
	'sa': { hiragana: 'さ', katakana: 'サ', romanization: 'sa', ipa: 'sa', consonant: 's', vowel: 'a' },
	'shi': { hiragana: 'し', katakana: 'シ', romanization: 'sh(i)', ipa: 'ɕ(i)', consonant: 's', vowel: 'i' },
	'su': { hiragana: 'す', katakana: 'ス', romanization: 'su', ipa: 'sɯ', consonant: 's', vowel: 'u' },
	'se': { hiragana: 'せ', katakana: 'セ', romanization: 'se', ipa: 'se', consonant: 's', vowel: 'e' },
	'so': { hiragana: 'そ', katakana: 'ソ', romanization: 'so', ipa: 'so', consonant: 's', vowel: 'o' },
	'za': { hiragana: 'ざ', katakana: 'ザ', romanization: 'za', ipa: 'za', consonant: 'z', vowel: 'a' },
	'ji': { hiragana: 'じ', katakana: 'ジ', romanization: 'ji', ipa: '(d)ʑi', consonant: 'z', vowel: 'i' },
	'zu': { hiragana: 'ず', katakana: 'ズ', romanization: 'zu', ipa: 'zɯ', consonant: 'z', vowel: 'u' },
	'ze': { hiragana: 'ぜ', katakana: 'ゼ', romanization: 'ze', ipa: 'ze', consonant: 'z', vowel: 'e' },
	'zo': { hiragana: 'ぞ', katakana: 'ゾ', romanization: 'zo', ipa: 'zo', consonant: 'z', vowel: 'o' },
	'ta': { hiragana: 'た', katakana: 'タ', romanization: 'ta', ipa: 'ta', consonant: 't', vowel: 'a' },
	'chi': { hiragana: 'ち', katakana: 'チ', romanization: 'chi', ipa: 'tɕi', consonant: 't', vowel: 'i' },
	'tsu': { hiragana: 'つ', katakana: 'ツ', romanization: 'tsu', ipa: 'tsɯ', consonant: 't', vowel: 'u' },
	'te': { hiragana: 'て', katakana: 'テ', romanization: 'te', ipa: 'te', consonant: 't', vowel: 'e' },
	'to': { hiragana: 'と', katakana: 'ト', romanization: 'to', ipa: 'to', consonant: 't', vowel: 'o' },
	'da': { hiragana: 'だ', katakana: 'ダ', romanization: 'da', ipa: 'da', consonant: 'd', vowel: 'a' },
	'de': { hiragana: 'で', katakana: 'デ', romanization: 'de', ipa: 'de', consonant: 'd', vowel: 'e' },
	'do': { hiragana: 'ど', katakana: 'ド', romanization: 'do', ipa: 'do', consonant: 'd', vowel: 'o' },
	'na': { hiragana: 'な', katakana: 'ナ', romanization: 'na', ipa: 'na', consonant: 'n', vowel: 'a' },
	'ni': { hiragana: 'に', katakana: 'ニ', romanization: 'ni', ipa: 'ni', consonant: 'n', vowel: 'i' },
	'nu': { hiragana: 'ぬ', katakana: 'ヌ', romanization: 'nu', ipa: 'nɯ', consonant: 'n', vowel: 'u' },
	'ne': { hiragana: 'ね', katakana: 'ネ', romanization: 'ne', ipa: 'ne', consonant: 'n', vowel: 'e' },
	'no': { hiragana: 'の', katakana: 'ノ', romanization: 'no', ipa: 'no', consonant: 'n', vowel: 'o' },
	'ha': { hiragana: 'は', katakana: 'ハ', romanization: 'ha', ipa: 'ha', consonant: 'h', vowel: 'a' },
	'hi': { hiragana: 'ひ', katakana: 'ヒ', romanization: 'hi', ipa: 'ç', consonant: 'h', vowel: 'i' },
	'fu': { hiragana: 'ふ', katakana: 'フ', romanization: 'fu', ipa: 'ɸɯ', consonant: 'h', vowel: 'u' },
	'he': { hiragana: 'へ', katakana: 'ヘ', romanization: 'he', ipa: 'he', consonant: 'h', vowel: 'e' },
	'ho': { hiragana: 'ほ', katakana: 'ホ', romanization: 'ho', ipa: 'ho', consonant: 'h', vowel: 'o' },
	'ba': { hiragana: 'ば', katakana: 'バ', romanization: 'ba', ipa: 'ba', consonant: 'b', vowel: 'a' },
	'bi': { hiragana: 'び', katakana: 'ビ', romanization: 'bi', ipa: 'bi', consonant: 'b', vowel: 'i' },
	'bu': { hiragana: 'ぶ', katakana: 'ブ', romanization: 'bu', ipa: 'bɯ', consonant: 'b', vowel: 'u' },
	'be': { hiragana: 'べ', katakana: 'ベ', romanization: 'be', ipa: 'be', consonant: 'b', vowel: 'e' },
	'bo': { hiragana: 'ぼ', katakana: 'ボ', romanization: 'bo', ipa: 'bo', consonant: 'b', vowel: 'o' },
	'pa': { hiragana: 'ぱ', katakana: 'パ', romanization: 'pa', ipa: 'pa', consonant: 'p', vowel: 'a' },
	'pi': { hiragana: 'ぴ', katakana: 'ピ', romanization: 'pi', ipa: 'pi', consonant: 'p', vowel: 'i' },
	'pu': { hiragana: 'ぷ', katakana: 'プ', romanization: 'pu', ipa: 'pɯ', consonant: 'p', vowel: 'u' },
	'pe': { hiragana: 'ぺ', katakana: 'ペ', romanization: 'pe', ipa: 'pe', consonant: 'p', vowel: 'e' },
	'po': { hiragana: 'ぽ', katakana: 'ポ', romanization: 'po', ipa: 'po', consonant: 'p', vowel: 'o' },
	'ma': { hiragana: 'ま', katakana: 'マ', romanization: 'ma', ipa: 'ma', consonant: 'm', vowel: 'a' },
	'mi': { hiragana: 'み', katakana: 'ミ', romanization: 'mi', ipa: 'mi', consonant: 'm', vowel: 'i' },
	'mu': { hiragana: 'む', katakana: 'ム', romanization: 'mu', ipa: 'mɯ', consonant: 'm', vowel: 'u' },
	'me': { hiragana: 'め', katakana: 'メ', romanization: 'me', ipa: 'me', consonant: 'm', vowel: 'e' },
	'mo': { hiragana: 'も', katakana: 'モ', romanization: 'mo', ipa: 'mo', consonant: 'm', vowel: 'o' },
	'ya': { hiragana: 'や', katakana: 'ヤ', romanization: 'ya', ipa: 'ja', consonant: 'y', vowel: 'a' },
	'yu': { hiragana: 'ゆ', katakana: 'ユ', romanization: 'yu', ipa: 'jɯ', consonant: 'y', vowel: 'u' },
	'yo': { hiragana: 'よ', katakana: 'ヨ', romanization: 'yo', ipa: 'jo', consonant: 'y', vowel: 'o' },
	'ra': { hiragana: 'ら', katakana: 'ラ', romanization: 'ra', ipa: 'ɾa', consonant: 'r', vowel: 'a' },
	'ri': { hiragana: 'り', katakana: 'リ', romanization: 'ri', ipa: 'ɾʲ', consonant: 'r', vowel: 'i' },
	'ru': { hiragana: 'る', katakana: 'ル', romanization: 'ru', ipa: 'ɾɯ', consonant: 'r', vowel: 'u' },
	're': { hiragana: 'れ', katakana: 'レ', romanization: 're', ipa: 'ɾe', consonant: 'r', vowel: 'e' },
	'ro': { hiragana: 'ろ', katakana: 'ロ', romanization: 'ro', ipa: 'ɾo', consonant: 'r', vowel: 'o' },
	'wa': { hiragana: 'わ', katakana: 'ワ', romanization: 'wa', ipa: 'ɯa', consonant: 'w', vowel: 'a' },
	'wi': { hiragana: 'ゐ', katakana: 'ヰ', romanization: 'wi', ipa: 'ɯi', consonant: 'w', vowel: 'i' },
	'we': { hiragana: 'ゑ', katakana: 'ヱ', romanization: 'we', ipa: 'ɯe', consonant: 'w', vowel: 'e' },
	'wo': { hiragana: 'を', katakana: 'ヲ', romanization: 'wo', ipa: 'ɯo', consonant: 'w', vowel: 'o' },
	'n': { hiragana: 'ん', katakana: 'ン', romanization: 'n', ipa: 'n, ɲ, ŋ, ɴ', consonant: 'n', vowel: '' },
} as const
